# app/util/aggregate_cpi_graphs.py

import plotly.express as px
import streamlit as st
import pandas as pd

def plot_cpi_over_time(df: pd.DataFrame, selected_countries: list):
    df_filtered_plot = df[df['COUNTRY_NAME'].isin(selected_countries)].copy()

    fig_cpi_time = px.line(
        df_filtered_plot,
        x='Time',
        y='OBS_VALUE',
        color='COUNTRY_NAME',
        markers=True,
        labels={'Time': 'Year', 'OBS_VALUE': 'CPI Value'},
        title='Aggregate CPI Over Time by Country',
        template='plotly_white'
    )
    fig_cpi_time.update_layout(hovermode='x unified', title_font_size=20)
    st.plotly_chart(fig_cpi_time, use_container_width=True)


def plot_cpi_stability_bar(stability_df: pd.DataFrame):
    # FIX: Use 'CPI_Stability_Score' as generated by calculate_cpi_stability
    fig_stab = px.bar(
        stability_df,
        x='COUNTRY_NAME',
        y='CPI_Stability_Score', # CHANGED from 'YoY_StdDev'
        text=stability_df['CPI_Stability_Score'].round(2), # CHANGED from 'YoY_StdDev'
        labels={'CPI_Stability_Score': 'Std. Dev of YoY % Change', 'COUNTRY_NAME': 'Country'}, # CHANGED label
        title='Top 10 CPI Stable Countries (Lower Score = More Stable)', # Clarified title
        template='plotly_white'
    )
    fig_stab.update_traces(marker_color='seagreen')
    fig_stab.update_layout(xaxis_title_text='')
    st.plotly_chart(fig_stab, use_container_width=True)


def plot_cpi_population_scatter(df_plot_cpi_pop: pd.DataFrame, selected_plot_year: int):
    # FIX: Use 'Avg_Annual_CPI_Value' as generated by prepare_cpi_population_scatter_data
    fig_cpi_pop = px.scatter(
        df_plot_cpi_pop,
        x="Population",
        y="Avg_Annual_CPI_Value", # CHANGED from "Average CPI"
        color="COUNTRY_NAME",
        size="Population",
        hover_name="COUNTRY_NAME",
        log_x=True,
        title=f"Average CPI vs. Population for {selected_plot_year}",
        labels={
            "Population": "Population",
            "Avg_Annual_CPI_Value": "Average Consumer Price Index (Index: 2015=100)" # CHANGED label
        },
        height=600,
        template='plotly_white'
    )
    fig_cpi_pop.update_layout(hovermode="closest", title_font_size=20)
    st.plotly_chart(fig_cpi_pop, use_container_width=True)